[tool.ruff]
line-length = 100
select = ["E","F","I","UP"]

[tool.mypy]
python_version = "3.10"
warn_unused_ignores = true
warn_return_any = true
strict_optional = true

[tool.pytest.ini_options]
addopts = "-q"
