model:
  dim: 2560
  n_heads: 64
  n_kv_groups: 4
  d_k: 192
  d_v: 128
nsa:
  l: 32
  d: 16
  l_sel: 64
  n_sel: 16
  w: 512
  phi: "avg"
runtime:
  precision: "bf16"
  use_flash: true
  use_triton_sel: false
  compile_cmp_win: false
  fa2_min_len_win: 999999  # Disable FA-2 on RTX 4090 (SM 8.9) by default; override via NSA_FA2_FORCE=1 for experiments
  fa2_min_len_cmp: 999999  # Disable FA-2 on RTX 4090 (SM 8.9) by default; override via NSA_FA2_FORCE=1 for experiments
  sel_triton_min_L: 4096 # Permanently disable Triton selection on RTX 4090 (see ADR); use SDPA fallback
train:
  lr: 3.0e-4
  warmup_steps: 50
  max_grad_norm: 1.0
