name: CI Version Matrix (CPU)

on:
  push:
  pull_request:

jobs:
  cpu-tests:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python: ["3.11"]
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python }}
      - name: Install deps (CPU)
        run: |
          python -m pip install -U pip
          python -m pip install -U uv
          uv venv -p 3.11 .venv
          uv pip sync requirements-cpu.txt
      - name: Lint and type check
        run: |
          uv run ruff check . || true
          uv run mypy nsa || true
      - name: Run CPU tests (subset)
        run: |
          PYTHONPATH=. uv run pytest -q nsa/tests/test_masks.py nsa/tests/test_block_math.py nsa/tests/test_equiv_small.py nsa/tests/test_group_consistency.py nsa/tests/test_decode_counters.py nsa/tests/test_packing_utils.py
      - name: Print routing summary (for diagnostics)
        run: |
          uv run python scripts/print_routing.py || true
