name: CI

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
            python-version: '3.11'

      - name: Install uv and deps
        run: |
          python -m pip install -U pip
          python -m pip install -U uv
          uv venv -p 3.11 .venv
          uv pip sync requirements-cpu.txt
          uv pip install -e .

      - name: Environment diagnostics
        run: |
          uv run python -V
          uv run python -c "import sys; print('sys.executable', sys.executable)"
          uv run python -c "import sys; print('PYTHONPATH', sys.path[0])"
          uv run python -c "print('diagnostics ok')" || true

      - name: Lint (ruff)
        run: |
          uv run ruff --version || true
          uv run ruff check . || true

      - name: Type check (mypy)
        run: |
          uv run mypy --version || true
          uv run mypy nsa || true

      - name: Collect tests (CPU)
        env:
          PYTHONPATH: "."
          PYTEST_DISABLE_PLUGIN_AUTOLOAD: "1"
        run: |
          uv run python -m pytest --collect-only -q || true

      - name: Run tests (CPU)
        env:
          PYTHONPATH: "."
          PYTEST_DISABLE_PLUGIN_AUTOLOAD: "1"
        run: |
          uv run python -m pytest -q -vv | tee test-output.txt

      - name: Upload test log
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: cpu-test-log
          path: test-output.txt

  build-batched-smoke:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
            python-version: '3.11'

      - name: Install uv and deps
        run: |
          python -m pip install -U pip
          python -m pip install -U uv
          uv venv -p 3.11 .venv
          uv pip sync requirements-cpu.txt
          uv pip install -e .

      - name: Run batched prefill smoke (CPU)
        env:
          NSA_PREFILL_BATCHED: '1'
          PYTHONPATH: '.'
          PYTEST_DISABLE_PLUGIN_AUTOLOAD: "1"
        run: |
          uv run python -m pytest -q -vv \
            nsa/tests/test_equiv_small.py \
            nsa/tests/test_equiv_full_coverage.py \
            nsa/tests/test_decode_reads_trend.py \
            nsa/tests/test_phi_mlp_equiv.py

      - name: Upload batched smoke log
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: cpu-batched-smoke-log
          path: test-output.txt
