name: Secrets Scan

on:
  pull_request:
  push:

jobs:
  scan:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Install ripgrep
        run: sudo apt-get update && sudo apt-get install -y ripgrep
      - name: Scan for secret patterns (non-blocking)
        continue-on-error: true
        run: |
          echo "Scanning for potential secrets..."
          rg --version
          # Common token patterns; exclude git/venv/build/artifacts
          rg -n --hidden \
            -g '!.git' -g '!.venv' -g '!artifacts' -g '!bench/*.csv' \
            -e 'hf_[A-Za-z0-9]{36,}' \
            -e 'AKIA[0-9A-Z]{16}' \
            -e 'ASIA[0-9A-Z]{16}' \
            -e '-----BEGIN (?:RSA|EC|OPENSSH) PRIVATE KEY-----' \
            -e 'xox[baprs]-[0-9A-Za-z-]+' \
            -e 'aws_secret_access_key' \
            -e 'BEGIN OPENSSH PRIVATE KEY' \
            || true
          echo "Scan complete. Investigate any matches above before merging."
